import React from 'react';
export default function Home(){
return(

    <div className='container-fluid' style={{backgroundColor:'white', padding: "1%",
        color: "#282c34",
        textAlign: "justify",
        boxSizing: "border-box"
        }}>
 <h3>The "Luminaria Spectacle" is a mesmerizing festival that has never been seen before. Held in a vast, glowing forest, the event transforms the landscape into a kaleidoscope of colors and lights.
 <br></br>
    The festival begins with a procession of lantern-carrying participants, their clothes and accessories adorned with intricate, bioluminescent patterns that react to their movements. As night falls, the forest floor comes alive with a sea of candles and glow sticks, creating a shimmering, iridescent carpet that stretches as far as the eye can see. Meanwhile, ethereal soundscapes and melodies fill the air, generated by an orchestra of instruments crafted from the forest's own natural elements – trees, rocks, and water. As the night wears on, the luminescent trees themselves begin to sway in time with the music, their branches morphing into dazzling displays of light and shadow.
    <br></br>
    The Luminaria Spectacle is an otherworldly celebration that redefines the boundaries between nature, art, and magic.</h3>  

    <h3>The "Luminaria Spectacle" is a mesmerizing festival that has never been seen before. Held in a vast, glowing forest, the event transforms the landscape into a kaleidoscope of colors and lights.
 <br></br>
    The festival begins with a procession of lantern-carrying participants, their clothes and accessories adorned with intricate, bioluminescent patterns that react to their movements. As night falls, the forest floor comes alive with a sea of candles and glow sticks, creating a shimmering, iridescent carpet that stretches as far as the eye can see. Meanwhile, ethereal soundscapes and melodies fill the air, generated by an orchestra of instruments crafted from the forest's own natural elements – trees, rocks, and water. As the night wears on, the luminescent trees themselves begin to sway in time with the music, their branches morphing into dazzling displays of light and shadow.
    <br></br>
    The Luminaria Spectacle is an otherworldly celebration that redefines the boundaries between nature, art, and magic.</h3>  
 </div>
)
}